apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-deployment
  namespace: fprotect
  labels:
    app: ubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
      - name: ubuntu
        image: reg.longph.works/ubuntu-test
        imagePullPolicy: IfNotPresent
        imagePullSecrets:
        - name: regcred
        ports:
        - containerPort: 80